# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'unbrowsed'
copyright = '2025, Valentino Gagliardi'
author = 'Valentino Gagliardi'
release = '0.1.0a9'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

# Add any Sphinx extension module names here, as strings
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.intersphinx",
    "sphinx.ext.viewcode",
]

# MyST parser configuration
myst_enable_extensions = [
    'colon_fence',             # Enable ::: code blocks
    'deflist',                 # Enable definition lists
]

# Autodoc configuration
autodoc_default_options = {
    'members': True,
    'undoc-members': True,
    'show-inheritance': True,
}

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files
exclude_patterns = [
    ".venv",
    "_build",
]

# The language for content autogenerated by Sphinx
language = 'en'

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

# The theme to use for HTML and HTML Help pages

html_theme = "furo"

# -- Intersphinx configuration -----------------------------------------------
# This allows you to link to other projects' documentation
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'selectolax': ('https://selectolax.readthedocs.io/en/latest/', None),
}

# -- Setup for autodoc -------------------------------------------------------
# Make sure the package is in the Python path
import os
import sys
sys.path.insert(0, os.path.abspath('../../src'))
